### ISSUE TITLE
MOSA Test Generation fails with MarshalException

### ISSUE THREAD

**Issue by schweikl** [VoglSebastian/evosuite#26]
### Context
When generating tests via the `DynaMOSA` algorithm a `java.rmi.MarshalException` is thrown.

### Steps to Reproduce

1. Download the SF110 corpus of classes
2. Check out the `selfType` branch
3. Change EvoSuite's working directory to the project `47_dvd-homevideo`
4. Run EvoSuite with the `DynaMOSA` algorithm

### EvoSuite Arguments
```
-Dalgorithm=DynaMOSA -Dstrategy=MOSuite -generateMOSuite -Dclient_on_thread=true -class Menu
```

### Current Result
At the end of the test generation process EvoSuite crashes with a `java.rmi.MarshalException`. Full stack trace:
```
[MASTER] 15:57:55.560 [pool-3-thread-1] ERROR ClientNodeImpl - Error when generating tests for: Menu with seed 1597327002141. Configuration id : null
java.rmi.MarshalException: error marshalling arguments; nested exception is: 
	java.io.NotSerializableException: org.evosuite.utils.BudgetConsumptionMonitor
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:160) ~[na:1.8.0_262]
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:235) ~[na:1.8.0_262]
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:180) ~[na:1.8.0_262]
	at com.sun.proxy.$Proxy6.evosuite_collectTestGenerationResult(Unknown Source) ~[na:na]
	at org.evosuite.rmi.service.ClientNodeImpl.lambda$startNewSearch$0(ClientNodeImpl.java:160) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_262]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_262]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_262]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_262]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_262]
Caused by: java.io.NotSerializableException: org.evosuite.utils.BudgetConsumptionMonitor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_262]
	at java.util.ArrayList.writeObject(ArrayList.java:768) ~[na:1.8.0_262]
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_262]
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1154) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_262]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_262]
	at sun.rmi.server.UnicastRef.marshalValue(UnicastRef.java:293) ~[na:1.8.0_262]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:155) ~[na:1.8.0_262]
	... 9 common frames omitted
```

**Comment by schweikl** [comment]
Seems the issue is that `BudgetConsumptionMonitor` is not `Serializable`. Simply saying
```Java
public class BudgetConsumptionMonitor implements Serializable {
```
already fixes the problem for me. (I just tried that and it worked.)

**Comment by gofraser** [comment]
You also need to set a serialVersionUID. Fix coming.

**Comment by schweikl** [comment]
Thanks, #27 has been merged. This fixes this issue.
